name: Valgrind Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dynamic Analysis
      run: cd 3_Implementation
    - name: valgrind
      run: .valgrind ./a.out &> valgrind.txt
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
